# Generated by Django 4.2.6 on 2023-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomplaint',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0),
        ),
    ]
