# Generated by Django 4.2.6 on 2023-11-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm', '0004_alter_usercomplaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaint',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
